### ISSUE TITLE
suggestion for improvement

### ISSUE THREAD

**Issue by Heythem-zouaoui** [mobizt/ESP-Google-Sheet-Client#25]
I noticed that this part of fonction "GSheet.setTokenCallback(tokenStatusCallback);"
enter three times to the other fonction "void tokenStatusCallback(TokenInfo info)"
and the issue is that some time it success and in other it fail so it take a lot of time that the wdt is triggered, this is my terminal 
when it fail:

STA IP Address: 192.168.1.103
Google Sheet Client v1.4.3

Token info: type = OAuth2.0 access token, status = on initializing
Token info: type = OAuth2.0 access token, status = on signing

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

Exception (4):
epc1=0x40247506 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: sys
sp: 3ffefdf0 end: 3fffffb0 offset: 0160
3ffeff50:  00001e94 3fff019c 3fff0298 3fff029e  
3ffeff60:  3fff029a 3fff0212 3fff00fa 00000000  
3ffeff70:  00000045 00000044 00007cf3 3fff0328  
3ffeff80:  3fff0212 00000002 00001b6c 00000040  
3ffeff90:  00000000 00000000 00000001 00000001

**Comment by mobizt** [comment]
The library was intensively tested and it works normally.

This is not just the test to prove this, the core code also used in my other libraries too which works perfectly for almost five years.

The first thing is you have to debug your code in case memory leaks and stack overflow as the wdt reset is just because system tasks failure.

**Comment by mobizt** [comment]
You also have to set the correct heap size in ESP8266, see the Readme for how to.
