### ISSUE TITLE
GS_TCP_Client cannot be instantiated (abstract class) due to missing connect() overrides

### ISSUE THREAD

**Issue by LGermanoJr** [mobizt/ESP-Google-Sheet-Client#46]
**Describe the bug**
When compiling for ESP32 Arduino Core version 3.1.0, I get the following error: invalid new-expression of abstract class type 'GS_TCP_Client'

This is because GS_TCP_Client inherits from `Client` but does not implement the two new `connect()` overloads with a timeout parameter:

virtual int connect(IPAddress ip, uint16_t port, int32_t timeout) = 0;
virtual int connect(const char* host, uint16_t port, int32_t timeout) = 0;

**To Reproduce**
Which ESP32 Arduino core version you’re using 3.1.0.

**Actual Behavior**
The library tries to do *client = new GS_TCP_Client(), but fails because GS_TCP_Client is still abstract (no overrides for the new connect() methods).

**Expected behavior**
GS_TCP_Client should compile successfully without error.

**IDE and its version:**
 - Arduino, IDE
 - Version 2.3.4

**Proposed Fix**
In GS_TCP_Client.h, add prototypes for the new connect overloads:
virtual int connect(IPAddress ip, uint16_t port, int32_t timeout) override;
virtual int connect(const char *host, uint16_t port, int32_t timeout) override;

GS_TCP_Client.cpp, implement them (even if you simply defer to the version without a custom timeout):

int GS_TCP_Client::connect(IPAddress ip, uint16_t port, int32_t timeout) {
  // E.g., ignore the custom timeout (or implement your own logic):
  return connect(ip, port);
}

int GS_TCP_Client::connect(const char* host, uint16_t port, int32_t timeout) {
  // Similarly:
  return connect(host, port);
}

Note: Suggested resolution solution is not tested.

**Comment by mobizt** [comment]
This is not a bug from library.

This issue introduces in ESP32 Arduino Core v3.1.0 that the additional connect methods are added in `Client.h` and breaks the Arduino API.

It causes compilation error in all Client derived classes on ESP32 core v3.1.0 e.g. Ethernet, ArduinoHttpClient, ArduinoMqttClient, TinyGSMClient ect.

It is not good idea to add those method to `Client.h` but the one in ESP32 core team do this because of gcc.

The better workaround was submitted in ESP32 Arduino repo [PR #10776](https://github.com/espressif/arduino-esp32/pull/10776/files).

I will apply the fix soon.

**Comment by mobizt** [comment]
You can update the library to [v1.4.6](https://github.com/mobizt/ESP-Google-Sheet-Client/releases/tag/v1.4.6) to fix the issue.
