### ISSUE TITLE
problems with GSheet.ready() = 0

### ISSUE THREAD

**Issue by DrWino** [mobizt/ESP-Google-Sheet-Client#9]
I have been using your excellent library to send data from ESP32 to Google sheets. It works quite well - I send a data String about every 5 minutes. The only problem is it seems to hang after a few hours with GSheets.ready() returning 0.

... in setup()

GSheet.begin(CLIENT_MAIL, PROJECT_ID, PRIVATE_KEY);

... then in loop every 5 minutes
ready = GSheet.ready();
if (ready) GSheet.append( ...... )

The problem is I get ready = false and repeating the loop does not clear it. Restarting the program does. I have a workaround by using ESP.restart() if the program hangs and then it runs correctly until the next hang. Not an elegant solution - wondering if you have any insights.

**Comment by mobizt** [comment]
The callback will show what's currently process, you should assign this.
https://github.com/mobizt/ESP-Google-Sheet-Client/blob/master/examples/Spreadsheets/Create/Create.ino#L67

Do not call something like this to wait for the token to finish because it will bock all other authentication tasks to perform.

while (!GSheet.ready())
{

}

This library works as normally without problems. It is the splitting project from my Firebase libraries which the token authentication processes are handled properly.

**Comment by DrWino** [comment]
I am sure your library works correctly. Not quite sure about how to handle the callback in your instructions. 
In your examples you do not use the callback. You just check the GSheet.ready().
So I am missing something.
But I will try to figure it out. I am so close close to a working system !

**Comment by mobizt** [comment]
You will see the information about the authentication status from the callback.

Evey task runs inside the GSheet.ready() will send the status to the callback.

The access token in your case is expired and you should look at the callback information, why the re-authentication has failed.

You will know what's the problems are e.g., networks error, connection error from the callback.

You also need to enable the Arduino IDE debug options for, SSL WiFi , OOM which will go in-dept for the SSL, memory and network status.

You may get the debug info about SSL/TLS handshake fail when your device free memory is running low.

**Comment by mobizt** [comment]
You never post about the callback info here and I can't help without that information.
